create table lancamento (
    CODIGO BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(50) NOT NULL,
    DATA_VENCIMENTO DATE NOT NULL,
    DATA_PAGAMENTO DATE,
    VALOR DECIMAL(10,2) NOT NULL,
    OBSERVACAO VARCHAR(100),
    TIPO VARCHAR(20) NOT NULL,
    CODIGO_CATEGORIA BIGINT(20) NOT NULL,
    CODIGO_PESSOA BIGINT(20) NOT NULL,
    FOREIGN KEY (CODIGO_CATEGORIA) REFERENCES CATEGORIA(CODIGO),
    FOREIGN KEY (CODIGO_PESSOA) REFERENCES PESSOA(CODIGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;